OpdrachtASP.NETCore/Models/ErrorViewModel.cs
namespace OpdrachtASP.NETCore.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

OpdrachtASP.NETCore/Models/Info.cs
using System.ComponentModel.DataAnnotations;

namespace OpdrachtASP.NETCore.Models
{
    public class Info
    {
        [Required]
        public string Name { get; set; }

        [Required]
        [EmailAddress]
        [Display(Name = "Email Address")]
        public string Email { get; set; }

        [Required]
        [StringLength(500, ErrorMessage = "Message is too long.")]
        public string Message { get; set; }
    }
}

OpdrachtASP.NETCore/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using OpdrachtASP.NETCore.Models;
using System.Diagnostics;

namespace OpdrachtASP.NETCore.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

OpdrachtASP.NETCore/Controllers/InfoController.cs
using Microsoft.AspNetCore.Mvc;
using OpdrachtASP.NETCore.Models;

namespace OpdrachtASP.NETCore.Controllers 
{
    public class InfoController : Controller
    {
        public IActionResult Index()
        {
            return View(new Info()
            {
                Name = "",
                Email = "",
                Message = ""

            });
        }

        [HttpGet]
        public IActionResult Update() => View(new Info());


        [HttpPost]
        public IActionResult Update(Info info)
        {
            if (ModelState.IsValid is false)
                return View(info);

            return View("Index", info);
        }
    }
}

OpdrachtASP.NETCore/Views/Home/Index.cshtml
@using System.Globalization
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer ViewLocalizer
@{
    ViewData["Title"] = "Information";
}

<div class="text-center">
    @ViewLocalizer["Welcome to our website"] (@CultureInfo.CurrentCulture.NativeName)
</div>

OpdrachtASP.NETCore/Views/Info/Index.cshtml
@model OpdrachtASP.NETCore.Models.Info

@{
    ViewData["Title"] = "Home Page";
}


<div class="text-centre">
    <p>Name: @Model.Name</p>
    <p>Email: @Model.Email</p>
    <p>Message: @Model.Message</p>
</div>






<a asp-controller="Info" asp-action="Update"><button class="btn btn-primary">Update</button></a>

OpdrachtASP.NETCore/Views/Info/Update.cshtml
@model OpdrachtASP.NETCore.Models.Info

@{
    Layout = "_FormLayout";
}


<form asp-controller="Info" asp-action="Update">
    Name:  <input asp-for="Name" /> <br />
    <span asp-validation-for="Name"></span><br/>
    Email:  <input asp-for="Email" /> <br />
    <span asp-validation-for="Email"></span><br />
    Message: <textarea asp-for="Message"></textarea><br />
    <span asp-validation-for="Message"></span><br /><br />
    <button type="submit">Submit</button>
</form>

OpdrachtASP.NETCore/Views/Shared/_FormLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - OpdrachtASP.NETCore</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/FormLayout.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/OpdrachtASP.NETCore.styles.css" asp-append-version="true" />
</head>
<body>
    
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

OpdrachtASP.NETCore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - OpdrachtASP.NETCore</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/OpdrachtASP.NETCore.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">OpdrachtASP.NETCore</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Info" asp-action="Index">Information</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - OpdrachtASP.NETCore - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>